version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    build: ./etc/database/
    env_file:
      - .env.example

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - api


  recsys_api:
    build: ./src
#    restart: always
    ports:
      - "8080:8080"
#    depends_on:
#      - postgres
    env_file:
      - .env.example

