version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    build: etc/recsys_database/
    ports:
      - "5432:5432"
    volumes:
      - ./etc/recsys_database/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - src/recsys_api/.env

  recsys_api:
    build:
      context: ./src
      dockerfile: src/recsys_api/Dockerfile
#    ports:
#      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - src/recsys_api/.env

  recsys_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/recsys_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/recsys_nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - recsys_api


