version: "3.8"
services:
  transporter:
    build: ./etl_service/sql_to_pg/
    container_name: transporter
    env_file:
    - ./etl_service/webvars_example.env
    depends_on:
      - db
  db:
    build: ./etl_service/database/
    container_name: db
    env_file:
    - ./etl_service/dbvars_example.env
  
  etl:
    build: ./etl_service/postgres_to_es
    container_name: etl
    depends_on:
      - es
    env_file:
    - ./etl_service/dbvars_example.env

  es:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 3
