@startuml
'https://plantuml.com/component-diagram

[NGINX]
[UGC]

package "RecSys" {
  [Prompt generator]
  [NGINX] --> [RecAPI]
  [Prompt generator] --> [RabbitMQ]
  [RabbitMQ] <--> [Request manager]
  [Parser] --> [RabbitMQ]
  database RecDB
}

cloud {
    [GigaChat]
}

[RecAPI] --> [RecDB]
[Request manager] --> [GigaChat]
[Parser] --> [RecDB]
[RecAPI] --> [GigaChat]
[UGC] <-- [Prompt generator]
[AsyncAPI] <-- [Prompt generator]

@enduml