name: CI

on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r async_api_service/requirements.txt
          pip install -r auth_service/requirements.txt
          pip install -r ugc_service/requirements.txt
      - name: Run tests
        run: |
          pytest async_api_service/tests/test_empty.py
          pytest auth_service/tests
          pytest ugc_service/tests
